version: '2'
services:
  mysql:
    image: 'bitnami/mysql:8.0'
    volumes:
      - 'mysql_data:/bitnami/mysql'
    environment:
      - MYSQL_USER=bn_wordpress
      - MYSQL_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '81:8080'
      - '82:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mysql
    environment:
      - MARIADB_HOST=mysql
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mysql_data:
    driver: local
  wordpress_data:
    driver: local
